# Site settings
title: Matheus Borges Teixeira
description: Matheus' Profile
favicon: /assets/img/IMG_20241104_115933022.jpg
baseurl:
url: http://ddbullfrog.com
rss_url: /pages/atom.xml

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
# Build settings
markdown: kramdown

# Author settings
author:
  name: Matheus Borges Teixeira
  title: Project Manager, Software Engineer and Archer
  address: Berlin, Germany
  email: matheus.bt@gmail.com
  link: http://matheuswrites.wordpress.com
  github: matheuscodes
  linkedin: matheusworks
  leetcode: matheus-codes
  gavatar: /assets/img/IMG_20241104_115933022.jpg
